import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { isPublishedChannelRegistry } from "../../lib/lost-found-channel-schema";
import { isPublicLostFoundResponsibilityIndex } from "../../lib/lost-found-responsibility-schema";
import type { AdapterFile } from "./schemas";

const SITE_ARGUMENT = process.argv.find((argument) => argument.startsWith("--site="));
if (!SITE_ARGUMENT) {
  throw new Error(
    "Usage: npm run data:lost-found:publish-site -- --site=/absolute/path/to/site-repository"
  );
}

const siteRoot = resolve(SITE_ARGUMENT.slice("--site=".length));
const outputRoot = resolve(siteRoot, "public/berlin-lost-found");
const versionRoot = resolve(outputRoot, "v1");
const projectRoot = resolve(import.meta.dirname, "../..");

const channelPath = resolve(
  projectRoot,
  "public/berlin-lost-found-channels.json"
);
const responsibilityPath = resolve(
  projectRoot,
  "public/berlin-lost-found-responsibilities.json"
);
const coveragePath = resolve(
  projectRoot,
  "data/lost-found-crawler/coverage-report.json"
);
const adapterPath = resolve(
  projectRoot,
  "data/lost-found-crawler/adapters.json"
);

const channels = JSON.parse(await readFile(channelPath, "utf8"));
const responsibilities = JSON.parse(await readFile(responsibilityPath, "utf8"));
const coverage = JSON.parse(await readFile(coveragePath, "utf8"));
const adapters = JSON.parse(await readFile(adapterPath, "utf8")) as AdapterFile;

if (!isPublishedChannelRegistry(channels)) {
  throw new Error("Refusing to publish an invalid channel registry");
}
if (!isPublicLostFoundResponsibilityIndex(responsibilities)) {
  throw new Error("Refusing to publish an invalid responsibility index");
}
if (adapters.version !== 1 || !Array.isArray(adapters.adapters)) {
  throw new Error("Refusing to publish an invalid adapter registry");
}

function serialize(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function resource(content: string) {
  return {
    sha256: createHash("sha256").update(content).digest("hex"),
    bytes: Buffer.byteLength(content),
  };
}

const channelContent = serialize(channels);
const responsibilityContent = serialize(responsibilities);
const coverageContent = serialize(coverage);
const channelResource = resource(channelContent);
const responsibilityResource = resource(responsibilityContent);
const coverageResource = resource(coverageContent);
const datasetVersion = createHash("sha256")
  .update(channelResource.sha256)
  .update(responsibilityResource.sha256)
  .digest("hex")
  .slice(0, 16);
const publishedAt = new Date().toISOString();
const fillOnlyAdapters = adapters.adapters.filter(
  (adapter) => adapter.capability === "fill_only"
).length;
const reviewedSubmitAdapters = adapters.adapters.filter(
  (adapter) => adapter.capability === "reviewed_submit"
).length;

const manifest = {
  version: 1,
  datasetVersion,
  generatedAt:
    channels.generatedAt > responsibilities.generatedAt
      ? channels.generatedAt
      : responsibilities.generatedAt,
  publishedAt,
  resources: {
    channels: { path: "channels.json", ...channelResource },
    responsibilities: {
      path: "responsibilities.json",
      ...responsibilityResource,
    },
    coverage: { path: "coverage.json", ...coverageResource },
  },
  summary: {
    channels: channels.channels.length,
    reviewedVenues: coverage.summary.reviewedChannel,
    totalVenues: coverage.summary.totalVenues,
    fillOnlyAdapters,
    reviewedSubmitAdapters,
  },
};

const statusPage = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Berlin Lost &amp; Found data feed</title>
  <style>
    :root{font:16px/1.55 system-ui,sans-serif;color:#17212b;background:#f4f6f7}
    body{margin:0;padding:48px 20px}main{max-width:720px;margin:auto;background:#fff;border:1px solid #d8dee3;padding:32px}
    h1{margin:0 0 8px;font-size:28px}p{color:#56616b}dl{display:grid;grid-template-columns:1fr auto;gap:10px 24px;margin:28px 0}
    dt{color:#56616b}dd{margin:0;font-weight:650}a{color:#16385c}code{background:#eef1f3;padding:2px 5px}
  </style>
</head>
<body><main>
  <p>YULID.ORG · PUBLIC DATA</p>
  <h1>Berlin Lost &amp; Found data feed</h1>
  <p>A versioned, read-only snapshot generated by the reviewed local discovery pipeline. The mobile app validates the schema and falls back to its bundled snapshot if this feed is unavailable.</p>
  <dl>
    <dt>Dataset version</dt><dd>${datasetVersion}</dd>
    <dt>Generated</dt><dd>${manifest.generatedAt}</dd>
    <dt>Reviewed channels</dt><dd>${manifest.summary.channels}</dd>
    <dt>Reviewed venue records</dt><dd>${manifest.summary.reviewedVenues}</dd>
    <dt>Fill-only adapters</dt><dd>${fillOnlyAdapters}</dd>
    <dt>Reviewed-submit adapters</dt><dd>${reviewedSubmitAdapters}</dd>
  </dl>
  <p>Machine endpoint: <a href="./v1/manifest.json"><code>/berlin-lost-found/v1/manifest.json</code></a></p>
</main></body></html>\n`;

await mkdir(versionRoot, { recursive: true });
await writeFile(resolve(versionRoot, "channels.json"), channelContent);
await writeFile(
  resolve(versionRoot, "responsibilities.json"),
  responsibilityContent
);
await writeFile(resolve(versionRoot, "coverage.json"), coverageContent);
await writeFile(resolve(versionRoot, "manifest.json"), serialize(manifest));
await writeFile(resolve(outputRoot, "index.html"), statusPage);

console.log(
  `Published dataset ${datasetVersion}: ${manifest.summary.channels} channels, ${manifest.summary.reviewedVenues}/${manifest.summary.totalVenues} reviewed venue records, ${fillOnlyAdapters} fill-only adapters.`
);
